### ISSUE TITLE
1.14.3 Time is Forever Frozen

### ISSUE THREAD

**Issue by EnderGamingFilms** [OffLuffy/SmoothSleep#3]
After some time the console will be spammed and time will freeze on the server.

https://pastebin.com/nr138U1J

**Comment by FaberoM** [comment]
Is running fine on my server, which plugin version are you using and what server are you running?

**Comment by EnderGamingFilms** [comment]
Pretty late reply, but it was a you final check loop or something but it is now fixed from changing out some plugins

**Comment by EnderGamingFilms** [comment]
I lies it happened again :/

This is my console, its going crazy.
https://pastebin.com/kv3PttLq

**Comment by OffLuffy** [comment]
Sorry for the slow replies. Honestly didn't realize anyone was posting issues here rather than the Spigot discussion.

It looks like something is either tampering with Bukkit tasks or perhaps altering sleeping mechanics. If there is a plugin that is either repeatedly attempting to cancel tasks or causes the server to trigger PlayerBedEnterEvent several times (especially during the day when players can't normally enter beds), then this may happen. I haven't seen this happen before, so it seems like a plugin conflict. If you could share your plugins, we may be able to help isolate the issue.

**Comment by EnderGamingFilms** [comment]
AcceptTheRules*, AdvancedRegionMarket, ArmorStandTools, BeastWithDraw, ChatControl, ClearLag, CMI, CommandDoesNotExist, CoreProtect, CraftingStore, DeluxeCommands, DeluxeMenus, DeluxeTags*, DonatorJoinPlus, EasyBackup*, EasyBackupCore*, ExtraContexts*, HeadDatabase*, HolographicDisplays, Jobs, LiteBans*, LuckPerms, LWC, mcMMO, MineableSpawners, Minepacks, Multiverse-Core, Multiverse-Inventories, NerfPhantoms, PlaceholderAPI*, PlaytimePlus*, PlaytimeReward*, PlugMan, ProtocolLib, QuickShop, ServerListPlus*, SimpleRename, SpecializedCrates, SuperVanish, TheNewEconomy, Towny, TownyChat, TownyFlight*, TownyNameUpdater*, Vault, ViaVersion*, Votifier, VotingPlugin, Vouchers, WorldBorder, WorldEdit, WorldEditCUI, WorldGuard, WorldGuardExtraFlags

**Comment by OffLuffy** [comment]
There's a good chance CMI is interfering. Just looking at the spigot page, it looks like it already includes basically what SmoothSleep does. Assuming you'd rather keep the premium plugin, you may want to disable SmoothSleep and just configure CMI how you want.

**Comment by EnderGamingFilms** [comment]
I disable the cmi one because your plugin does it better, but it still might be breaking it

**Comment by OffLuffy** [comment]
I'm not sure if you'd be able to disable just the sleep mechanics of CMI in a way that would prevent it from modifying the events I'm using, so you'd likely need to completely uninstall it to see if it's the problem. Also not familiar with how PlugMan disables plugins, so not sure if that would work either.

**Comment by EnderGamingFilms** [comment]
I had it disabled in the config?

**Comment by OffLuffy** [comment]
Not sure what you're asking. Just saying if you still have CMI installed, but sleep mechanics disabled, it may still interfere. It's not open source, so I can't check how it's written.
