### ISSUE TITLE
While players heal with sleeping, Villagers do not.

### ISSUE THREAD

**Issue by kharidiron** [OffLuffy/SmoothSleep#4]
It is being reported to me by players on my server that villagers are not getting their HP back after a night spent sleeping. I'm not sure if they just don't have enough time to reach beds or if their healing algorithm just isn't getting kicked off. I'm running Minecraft 1.14.4, Spigot 2437, and plugin version 2.5.1.

**Comment by OffLuffy** [comment]
Wasn't even aware Villagers were meant to heal while sleeping. I can see how the plugin would interfere with this if the nights were passing by quickly. It's not doing anything fancy to speed up time, so things that happen overnight every so many ticks won't be sped up (and probably be cut short instead). I'll keep this in mind for the next version.

**Comment by OffLuffy** [comment]
In v2.6.0 (not currently released), I'm adding a feature that will heal villagers in the morning to full health at 5:30am (23500 ticks). It'll show a heart particle above them indicating they've been healed. This will only happen if the villager is in bed during that tick and can be disabled in the config.
