### ISSUE TITLE
Space in world name, world name does not exist.

### ISSUE THREAD

**Issue by twilightparadox** [OffLuffy/SmoothSleep#9]
Exactly what it sounds like. My server owner decided to make a world with a space in it `wipe 1`. Some plugins don't seem to work, and I want to figure this out. I have tried:
```
/ssaddworld 'wipe 1'
wipe\ 1
wipe\1
wipe_1
wipe-1
"wipe 1"
```
What do I do in this situation?

**Comment by OffLuffy** [comment]
Sorry for the late reply, I don't get notified of issues here. Someone has mentioned the world names with spaces in it before, but I doubt there's a better way to get it to work than just rename the world. Older versions of Minecraft didn't support white-space in the world names, so it's just been generally accepted that no white-space is best practice. It's just too niche of a problem to warrant changing as much as it'd require changing only to support a bad habit.
